version: "2.2"
services:
  nginx:
    image: nginx
    networks:
      staticnet:
        ipv4_address: 172.18.0.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx

  mysql:
    build: ./glasses_mysql
    networks:
      staticnet:
        ipv4_address: 172.18.0.3
    environment:
      MYSQL_ROOT_PASSWORD: zyhng
    restart: always
    volumes:
      - ./glasses_mysql/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis
    networks:
      staticnet:
        ipv4_address: 172.18.0.4
    command: redis-server --requirepass test

  web-node1:
    build: ./glasses/
    networks:
      staticnet:
        ipv4_address: 172.18.0.5

  web-node2:
    build: ./glasses/
    networks:
      staticnet:
        ipv4_address: 172.18.0.6

networks:
  staticnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
